services:
  postgres:
    image: postgis/postgis:17-3.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost -p 5432"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 1800s

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
    command: ["python", "-m", "floorheights.datamodel.cli"]

  martin:
    image: ghcr.io/maplibre/martin
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      # - RUST_LOG=debug
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend-dev:
    build:
      context: ./frontend
      target: builder
    volumes:
      - ./frontend/floor-heights:/app
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev -- --host"
    depends_on:
      - martin
      - backend-dev
    profiles:
      - dev

  frontend-prod:
    build:
      context: ./frontend
      target: nginx
    ports:
      - "80:80"
    depends_on:
      - martin
      - backend-prod
    profiles:
      - prod

  backend-dev:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - MAPS_HOST=http://martin:3000/
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app:/code/app
      - ./src:/code/floor-heights
    command: uvicorn app.main:app --reload --proxy-headers --host 0.0.0.0 --port 8080
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dev

  backend-prod:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - MAPS_HOST=http://martin:3000/
    ports:
      - "4001:4001"
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 4001
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - prod

volumes:
  postgres_data:
