services:
  postgres:
    image: postgis/postgis:17-3.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost -p 5432"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 1800s

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
    command: ["python", "-m", "floorheights.datamodel.cli"]

volumes:
  postgres_data:
