services:
  postgres:
    image: postgis/postgis:17-3.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    command: ["python", "app/cli.py"]

volumes:
  postgres_data:
