/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CategorisedLegendComponent: typeof import('./src/components/CategorisedLegendComponent.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    copy: typeof import('./src/components/GraduatedLegendComponent copy.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    FloorMeasureComponent: typeof import('./src/components/FloorMeasureComponent.vue')['default']
    GraduatedLegendComponent: typeof import('./src/components/GraduatedLegendComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageWindowComponent: typeof import('./src/components/ImageWindowComponent.vue')['default']
    LegendComponent: typeof import('./src/components/LegendComponent.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MenuButton: typeof import('./src/components/MenuButton.vue')['default']
    MenuComponent: typeof import('./src/components/MenuComponent.vue')['default']
    MenuPanels: typeof import('./src/components/MenuPanels.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Panel: typeof import('primevue/panel')['default']
    Select: typeof import('primevue/select')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
