"""Add primary_secondary address_point column

Revision ID: 10f58cb28fbe
Revises: 9053bd39a8cd
Create Date: 2025-05-30 00:47:32.094815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '10f58cb28fbe'
down_revision: Union[str, None] = '9053bd39a8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_point', sa.Column('primary_secondary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_point', 'primary_secondary')
    # ### end Alembic commands ###
