"""Add land use zone field for buildings

Revision ID: 11729c8a6fdd
Revises: 80cfa506e842
Create Date: 2025-05-15 04:40:07.074250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '11729c8a6fdd'
down_revision: Union[str, None] = '80cfa506e842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('land_use_zone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'land_use_zone')
    # ### end Alembic commands ###
