"""Add measure_range field to floor_measure

Revision ID: 1af3ceff9a62
Revises: 3a2a2ee6e864
Create Date: 2025-06-23 03:02:35.762859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1af3ceff9a62'
down_revision: Union[str, None] = '3a2a2ee6e864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floor_measure', sa.Column('measure_range', postgresql.NUMRANGE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floor_measure', 'measure_range')
    # ### end Alembic commands ###
