"""Rename accuracy_measure to confidence

Revision ID: 3a2a2ee6e864
Revises: b769c250b877
Create Date: 2025-06-19 02:10:40.537457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3a2a2ee6e864'
down_revision: Union[str, None] = 'b769c250b877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floor_measure', sa.Column('confidence', sa.Float(), nullable=True))
    op.drop_column('floor_measure', 'accuracy_measure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floor_measure', sa.Column('accuracy_measure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('floor_measure', 'confidence')
    # ### end Alembic commands ###
