"""Basic model definition, no relationships

Revision ID: 4d475a3db472
Revises: 
Create Date: 2024-10-22 00:56:00.467511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4d475a3db472'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_point',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_point_location', 'address_point', ['location'], unique=False, postgresql_using='gist')
    op.create_table('building',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outline', geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('height_ahd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_building_outline', 'building', ['outline'], unique=False, postgresql_using='gist')
    op.create_table('dataset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floor_measure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storey', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('accuracy_measure', sa.Float(), nullable=False),
    sa.Column('aux_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('method',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('method')
    op.drop_table('floor_measure')
    op.drop_table('dataset')
    op.drop_index('idx_building_outline', table_name='building', postgresql_using='gist')
    op.drop_table('building')
    op.drop_index('idx_address_point_location', table_name='address_point', postgresql_using='gist')
    op.drop_table('address_point')
    # ### end Alembic commands ###
