"""Add table to store floor height images

Revision ID: 80cfa506e842
Revises: c98909de550a
Create Date: 2025-05-08 00:01:33.712664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '80cfa506e842'
down_revision: Union[str, None] = 'c98909de550a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_measure_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('floor_measure_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['floor_measure_id'], ['floor_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('floor_measure_image')
    # ### end Alembic commands ###
