"""Set geometry CRS as GDA2020

Revision ID: 9053bd39a8cd
Revises: 11729c8a6fdd
Create Date: 2025-05-29 08:38:22.131627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9053bd39a8cd'
down_revision: Union[str, None] = '11729c8a6fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_point', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=7844, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               existing_nullable=False)
    op.alter_column('building', 'outline',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=7844, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'outline',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=7844, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               existing_nullable=False)
    op.alter_column('address_point', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=7844, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               existing_nullable=False)
    # ### end Alembic commands ###
