"""add cadastre table to support address-building spatial join

Revision ID: a1e4b33ac138
Revises: a8654f1d1d7a
Create Date: 2024-11-10 22:53:19.886606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a1e4b33ac138'
down_revision: Union[str, None] = 'a8654f1d1d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cadastre_geometry', 'cadastre', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cadastre_geometry', table_name='cadastre', postgresql_using='gist')
    op.drop_table('cadastre')
    # ### end Alembic commands ###
