"""include min and max building footprint height

Revision ID: a8654f1d1d7a
Revises: f3f2c4456068
Create Date: 2024-11-07 02:40:11.727280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a8654f1d1d7a'
down_revision: Union[str, None] = 'f3f2c4456068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('min_height_ahd', sa.Float(), nullable=False))
    op.add_column('building', sa.Column('max_height_ahd', sa.Float(), nullable=False))
    op.drop_column('building', 'height_ahd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('height_ahd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('building', 'max_height_ahd')
    op.drop_column('building', 'min_height_ahd')
    # ### end Alembic commands ###
