"""Added relationships and foreign keys between tables

Revision ID: b14374b999a4
Revises: 4d475a3db472
Create Date: 2024-10-22 06:03:13.992246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b14374b999a4'
down_revision: Union[str, None] = '4d475a3db472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_point_building_association',
    sa.Column('address_point_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['address_point_id'], ['address_point.id'], ),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('address_point_id', 'building_id')
    )
    op.create_table('floor_measure_dataset_association',
    sa.Column('floor_measure_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['floor_measure_id'], ['floor_measure.id'], ),
    sa.PrimaryKeyConstraint('floor_measure_id', 'dataset_id')
    )
    op.add_column('floor_measure', sa.Column('building_id', sa.UUID(), nullable=False))
    op.add_column('floor_measure', sa.Column('method_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'floor_measure', 'method', ['method_id'], ['id'])
    op.create_foreign_key(None, 'floor_measure', 'building', ['building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'floor_measure', type_='foreignkey')
    op.drop_constraint(None, 'floor_measure', type_='foreignkey')
    op.drop_column('floor_measure', 'method_id')
    op.drop_column('floor_measure', 'building_id')
    op.drop_table('floor_measure_dataset_association')
    op.drop_table('address_point_building_association')
    # ### end Alembic commands ###
