"""allow server-side uuid generation for buildings and addresses

Revision ID: f3f2c4456068
Revises: ca9457ce8546
Create Date: 2024-10-29 22:43:04.424130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f3f2c4456068'
down_revision: Union[str, None] = 'ca9457ce8546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "address_point",
        "id",
        server_default=sa.text("gen_random_uuid()"),
    )
    op.alter_column(
        "building",
        "id",
        server_default=sa.text("gen_random_uuid()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "address_point",
        "id",
        server_default=None,
    )
    op.alter_column(
        "building",
        "id",
        server_default=None,
    )
    # ### end Alembic commands ###
