name: Build on push develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: API Build and push develop to staging ECR
    strategy:
      matrix:
        build-details:
          - {path: ., dockerfile-file-name: backend/Dockerfile ,image-name: floor-heights/backend}
          - {path: frontend, dockerfile-file-name: Dockerfile, image-name: floor-heights/frontend}
    uses: ./.github/workflows/build-push-to-ecr.yml
    with:
      path: ${{ matrix.build-details.path }}
      dockerfile-file-name: ${{ matrix.build-details.dockerfile-file-name }}
      image-name: ${{ matrix.build-details.image-name }}
    secrets:
      aws-access-key-id: ${{ secrets.STAGING_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.STAGING_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.STAGING_AWS_REGION }}
      aws-account-id: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}
